import type {
  CareerPath,
  Difficulty,
  QuestionType,
  Technology,
  TopicMeta,
} from "@/types/interview";

export const BRAND = {
  name: "CodeZetta",
  product: "Interview Hub",
  tagline: "Master Your Next Tech Interview.",
  subtitle:
    "1,100+ carefully organized Frontend & Backend interview questions — from fundamentals to Tech Lead.",
} as const;

export const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  fresh: "Fresh / Intern",
  junior: "Junior",
  mid: "Mid-Level",
  senior: "Senior",
  lead: "Tech Lead",
};

export const QUESTION_TYPE_LABELS: Record<QuestionType, string> = {
  concept: "Concept",
  coding: "Live Coding",
  scenario: "Scenario",
  architecture: "Architecture",
  debugging: "Debugging",
  comparison: "Comparison",
  output: "Code Output",
  "best-practice": "Best Practice",
};

export const CAREER_PATH_TECH: Record<CareerPath, Technology[]> = {
  frontend: [
    "html",
    "css",
    "javascript",
    "typescript",
    "scss",
    "angular",
    "react",
    "nextjs",
    "vue",
  ],
  backend: ["javascript", "typescript", "nodejs", "nestjs"],
  fullstack: [
    "html",
    "css",
    "javascript",
    "typescript",
    "scss",
    "angular",
    "react",
    "nextjs",
    "vue",
    "nodejs",
    "nestjs",
  ],
};

export const TOPICS: TopicMeta[] = [
  {
    id: "html",
    name: "HTML",
    track: "frontend",
    group: "fundamentals",
    description: "Semantics, accessibility, forms, and browser fundamentals.",
    targetCount: 100,
    color: "#E34F26",
    categories: [
      { name: "Semantics", slug: "semantics" },
      { name: "Accessibility", slug: "accessibility" },
      { name: "Forms", slug: "forms" },
      { name: "Media", slug: "media" },
      { name: "SEO", slug: "seo" },
      { name: "APIs", slug: "apis" },
      { name: "Performance", slug: "performance" },
      { name: "Security", slug: "security" },
    ],
  },
  {
    id: "css",
    name: "CSS",
    track: "frontend",
    group: "fundamentals",
    description: "Layout, cascade, responsive design, and modern CSS.",
    targetCount: 100,
    color: "#1572B6",
    categories: [
      { name: "Cascade", slug: "cascade" },
      { name: "Selectors", slug: "selectors" },
      { name: "Box Model", slug: "box-model" },
      { name: "Flexbox", slug: "flexbox" },
      { name: "Grid", slug: "grid" },
      { name: "Responsive", slug: "responsive" },
      { name: "Animations", slug: "animations" },
      { name: "Performance", slug: "performance" },
    ],
  },
  {
    id: "javascript",
    name: "JavaScript",
    track: "both",
    group: "fundamentals",
    description: "Runtime, async, browser APIs, and production patterns.",
    targetCount: 100,
    color: "#F7DF1E",
    categories: [
      { name: "Execution Context", slug: "execution-context" },
      { name: "Scope", slug: "scope" },
      { name: "Hoisting", slug: "hoisting" },
      { name: "Closures", slug: "closures" },
      { name: "this", slug: "this" },
      { name: "Prototype", slug: "prototype" },
      { name: "OOP", slug: "oop" },
      { name: "Functional Programming", slug: "functional" },
      { name: "Async JavaScript", slug: "async" },
      { name: "Event Loop", slug: "event-loop" },
      { name: "Promises", slug: "promises" },
      { name: "Memory Management", slug: "memory" },
      { name: "DOM", slug: "dom" },
      { name: "Browser APIs", slug: "browser-apis" },
      { name: "Performance", slug: "performance" },
      { name: "Modules", slug: "modules" },
      { name: "Error Handling", slug: "error-handling" },
    ],
  },
  {
    id: "typescript",
    name: "TypeScript",
    track: "both",
    group: "fundamentals",
    description: "Types, generics, narrowing, and scalable type architecture.",
    targetCount: 100,
    color: "#3178C6",
    categories: [
      { name: "Types", slug: "types" },
      { name: "Interfaces", slug: "interfaces" },
      { name: "Generics", slug: "generics" },
      { name: "Utility Types", slug: "utility-types" },
      { name: "Type Narrowing", slug: "narrowing" },
      { name: "Type Guards", slug: "type-guards" },
      { name: "Classes", slug: "classes" },
      { name: "Decorators", slug: "decorators" },
      { name: "Advanced Types", slug: "advanced-types" },
      { name: "Conditional Types", slug: "conditional-types" },
      { name: "Mapped Types", slug: "mapped-types" },
      { name: "Type Inference", slug: "inference" },
      { name: "Type Safety", slug: "type-safety" },
      { name: "Architecture", slug: "architecture" },
    ],
  },
  {
    id: "scss",
    name: "SCSS",
    track: "frontend",
    group: "fundamentals",
    description: "Variables, mixins, architecture, and maintainable styles.",
    targetCount: 100,
    color: "#CF649A",
    categories: [
      { name: "Variables", slug: "variables" },
      { name: "Nesting", slug: "nesting" },
      { name: "Mixins", slug: "mixins" },
      { name: "Functions", slug: "functions" },
      { name: "Partials", slug: "partials" },
      { name: "Architecture", slug: "architecture" },
      { name: "Performance", slug: "performance" },
    ],
  },
  {
    id: "angular",
    name: "Angular",
    track: "frontend",
    group: "frameworks",
    description: "Components, DI, Signals, RxJS, and enterprise patterns.",
    targetCount: 100,
    color: "#DD0031",
    categories: [
      { name: "Components", slug: "components" },
      { name: "Templates", slug: "templates" },
      { name: "Dependency Injection", slug: "dependency-injection" },
      { name: "Change Detection", slug: "change-detection" },
      { name: "Signals", slug: "signals" },
      { name: "RxJS", slug: "rxjs" },
      { name: "Routing", slug: "routing" },
      { name: "Forms", slug: "forms" },
      { name: "HTTP", slug: "http" },
      { name: "Guards", slug: "guards" },
      { name: "Interceptors", slug: "interceptors" },
      { name: "Performance", slug: "performance" },
      { name: "SSR", slug: "ssr" },
      { name: "Hydration", slug: "hydration" },
      { name: "Zoneless Angular", slug: "zoneless" },
      { name: "Architecture", slug: "architecture" },
      { name: "Testing", slug: "testing" },
      { name: "Security", slug: "security" },
    ],
  },
  {
    id: "react",
    name: "React",
    track: "frontend",
    group: "frameworks",
    description: "Hooks, rendering, performance, and modern React patterns.",
    targetCount: 100,
    color: "#61DAFB",
    categories: [
      { name: "Components", slug: "components" },
      { name: "JSX", slug: "jsx" },
      { name: "Props", slug: "props" },
      { name: "State", slug: "state" },
      { name: "Hooks", slug: "hooks" },
      { name: "useEffect", slug: "useeffect" },
      { name: "useMemo", slug: "usememo" },
      { name: "useCallback", slug: "usecallback" },
      { name: "Context", slug: "context" },
      { name: "Rendering", slug: "rendering" },
      { name: "Reconciliation", slug: "reconciliation" },
      { name: "Performance", slug: "performance" },
      { name: "State Management", slug: "state-management" },
      { name: "Server Components", slug: "server-components" },
      { name: "Architecture", slug: "architecture" },
      { name: "Testing", slug: "testing" },
    ],
  },
  {
    id: "nextjs",
    name: "Next.js",
    track: "frontend",
    group: "frameworks",
    description: "App Router, caching, SSR/SSG, and production Next.js.",
    targetCount: 100,
    color: "#000000",
    categories: [
      { name: "App Router", slug: "app-router" },
      { name: "Server Components", slug: "server-components" },
      { name: "Client Components", slug: "client-components" },
      { name: "Rendering", slug: "rendering" },
      { name: "SSR", slug: "ssr" },
      { name: "SSG", slug: "ssg" },
      { name: "ISR", slug: "isr" },
      { name: "Caching", slug: "caching" },
      { name: "Route Handlers", slug: "route-handlers" },
      { name: "Server Actions", slug: "server-actions" },
      { name: "Authentication", slug: "authentication" },
      { name: "Middleware", slug: "middleware" },
      { name: "Metadata", slug: "metadata" },
      { name: "SEO", slug: "seo" },
      { name: "Performance", slug: "performance" },
      { name: "Deployment", slug: "deployment" },
    ],
  },
  {
    id: "vue",
    name: "Vue.js",
    track: "frontend",
    group: "frameworks",
    description: "Composition API, reactivity, and Vue application design.",
    targetCount: 100,
    color: "#42B883",
    categories: [
      { name: "Components", slug: "components" },
      { name: "Reactivity", slug: "reactivity" },
      { name: "Composition API", slug: "composition-api" },
      { name: "Props & Emits", slug: "props-emits" },
      { name: "Directives", slug: "directives" },
      { name: "Routing", slug: "routing" },
      { name: "Pinia", slug: "pinia" },
      { name: "Performance", slug: "performance" },
      { name: "Architecture", slug: "architecture" },
      { name: "Testing", slug: "testing" },
    ],
  },
  {
    id: "nodejs",
    name: "Node.js",
    track: "backend",
    group: "backend",
    description: "Runtime, streams, security, and scalable Node services.",
    targetCount: 100,
    color: "#339933",
    categories: [
      { name: "Runtime", slug: "runtime" },
      { name: "Event Loop", slug: "event-loop" },
      { name: "Streams", slug: "streams" },
      { name: "Buffers", slug: "buffers" },
      { name: "File System", slug: "file-system" },
      { name: "Async Programming", slug: "async" },
      { name: "Modules", slug: "modules" },
      { name: "APIs", slug: "apis" },
      { name: "Express Concepts", slug: "express" },
      { name: "Authentication", slug: "authentication" },
      { name: "Security", slug: "security" },
      { name: "Performance", slug: "performance" },
      { name: "Scaling", slug: "scaling" },
      { name: "Clustering", slug: "clustering" },
      { name: "Processes", slug: "processes" },
      { name: "Memory", slug: "memory" },
      { name: "Error Handling", slug: "error-handling" },
    ],
  },
  {
    id: "nestjs",
    name: "NestJS",
    track: "backend",
    group: "backend",
    description: "Modules, DI, guards, pipes, and Nest architecture.",
    targetCount: 100,
    color: "#E0234E",
    categories: [
      { name: "Modules", slug: "modules" },
      { name: "Controllers", slug: "controllers" },
      { name: "Providers", slug: "providers" },
      { name: "Dependency Injection", slug: "dependency-injection" },
      { name: "Middleware", slug: "middleware" },
      { name: "Guards", slug: "guards" },
      { name: "Pipes", slug: "pipes" },
      { name: "Interceptors", slug: "interceptors" },
      { name: "Exception Filters", slug: "exception-filters" },
      { name: "DTOs", slug: "dtos" },
      { name: "Validation", slug: "validation" },
      { name: "Authentication", slug: "authentication" },
      { name: "Authorization", slug: "authorization" },
      { name: "ORM Concepts", slug: "orm" },
      { name: "Microservices", slug: "microservices" },
      { name: "Testing", slug: "testing" },
      { name: "Architecture", slug: "architecture" },
    ],
  },
];

export const TOPIC_MAP = Object.fromEntries(
  TOPICS.map((t) => [t.id, t]),
) as Record<Technology, TopicMeta>;

export const STORAGE_KEYS = {
  preferences: "cz_preferences_v1",
  progress: "cz_progress_v1",
  bookmarks: "cz_bookmarks_v1",
  mockHistory: "cz_mock_history_v1",
} as const;

export const QUESTION_COUNTS = [10, 20, 30, 50] as const;
